### ISSUE TITLE
TypeError: Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by LipingSun** [unional/komondor#188]
TypeError: Cannot read property 'name' of undefined

      at Object.isInstance [as support] (node_modules/komondor/src/instance/isInstance.ts:5:30)
      at plugin_1.plugins.find.p (node_modules/komondor/src/specAction.ts:73:38)
      at Array.find (native)
      at serializeEntry (node_modules/komondor/src/specAction.ts:73:26)
      at Object.keys.reduce (node_modules/komondor/src/specAction.ts:83:16)
          at Array.reduce (<anonymous>)
      at serializeEntry (node_modules/komondor/src/specAction.ts:82:31)
      at Object.keys.reduce (node_modules/komondor/src/specAction.ts:83:16)
          at Array.reduce (<anonymous>)
      at serializeEntry (node_modules/komondor/src/specAction.ts:82:31)
      at Object.keys.reduce (node_modules/komondor/src/specAction.ts:83:16)
          at Array.reduce (<anonymous>)
      at serializeEntry (node_modules/komondor/src/specAction.ts:82:31)
      at value.map.v (node_modules/komondor/src/specAction.ts:65:51)
          at Array.map (<anonymous>)
      at serializeEntry (node_modules/komondor/src/specAction.ts:65:42)

This is reproducible by running komondor test and set breakpoint at `isInstance.ts:5:30`

**Comment by unional** [comment]
Hi Liping,

I can't reproduce this.
Can you share how's your test look like?

I have tried:
```ts
const t = require('assert')
const a = require('assertron')
const axios = require('axios')
const komondor = require('komondor')

const { spec } = komondor

test('instance', async () => {
  class Foo {
    do() { return 1 }
  }
  const foo = new Foo()
  const s = await spec(foo)
  const actual = s.subject
  t.equal(actual.do(), 1)

  await s.done()
})
test('literal', async () => {
  const literal = { do() { return 1 } }
  await spec(literal) // Throws NotSpecable correctly
})
test('axios', async () => {
  const s = await spec(axios)
  const actual = s.subject
  a.satisfy(await actual.head('http://dummy.restapiexample.com/api/v1/employees'), {
    status: 200
  })

  await s.done()
})
```  

And they all seem to be working correctly.

`axios` is still not working, but it seems like it is an instance of class `Axios` internally, so `komondor` might able to support it before v7.
But I notice it is not working during simulate mode, looking into that right now.
